### PR TITLE
update pybind11 to v2.11.1

### LINKED ISSUE #361: Python 3.11+ Compile Error: incomplete type 'PyFrameObject'
## 🐛 Bug

When compiling with Python 3.11 the following error occurs:

```
2023-08-09T06:14:07.8531793Z      22 | typedef struct _frame PyFrameObject;
2023-08-09T06:14:07.8532107Z         |                ^~~~~~
2023-08-09T06:14:07.8532516Z   In file included from /opt/hostedtoolcache/Python/3.11.4/x64/include/python3.11/Python.h:38,
2023-08-09T06:14:07.8533187Z                    from /tmp/tmpeu6rdsdd/nle-0.9.0/third_party/pybind11/include/pybind11/detail/common.h:124,
2023-08-09T06:14:07.8533840Z                    from /tmp/tmpeu6rdsdd/nle-0.9.0/third_party/pybind11/include/pybind11/pytypes.h:12,
2023-08-09T06:14:07.8534482Z                    from /tmp/tmpeu6rdsdd/nle-0.9.0/third_party/pybind11/include/pybind11/cast.h:13,
2023-08-09T06:14:07.8535105Z                    from /tmp/tmpeu6rdsdd/nle-0.9.0/third_party/pybind11/include/pybind11/attr.h:13,
2023-08-09T06:14:07.8535743Z                    from /tmp/tmpeu6rdsdd/nle-0.9.0/third_party/pybind11/include/pybind11/pybind11.h:45,
2023-08-09T06:14:07.8536366Z                    from /tmp/tmpeu6rdsdd/nle-0.9.0/third_party/pybind11/include/pybind11/numpy.h:12,
2023-08-09T06:14:07.8536982Z                    from /tmp/tmpeu6rdsdd/nle-0.9.0/third_party/converter/pyconverter.cc:8:
2023-08-09T06:14:07.8537788Z   /tmp/tmpeu6rdsdd/nle-0.9.0/third_party/pybind11/include/pybind11/pybind11.h:2296:30: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
2023-08-09T06:14:07.8538503Z    2296 |             frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
2023-08-09T06:14:07.8538892Z         |                              ^~~~~~~~~~~~~~~~
```

## To Reproduce (on Ubuntu 22.04)

1. sudo add-apt-repository -y ppa:deadsnakes/ppa
2. sudo apt install python3.11 python3.11-dev
3. pip install nle
(assumes installing cmake and other [build instructions](https://github.com/facebookresearch/nle#installation) have already been performed)

## Expected behavior

Actually compile ;)

## Additional context

This occurs because [Python 3.11 restructured the PyFrameObject](https://docs.python.org/3.11/whatsnew/3.11.html) structure (search that link for "PyFrameObject fields") which breaks old versions of pybind11. Currently the [`third-party` directory](https://github.com/facebookresearch/nle/tree/main/third_party) of NLE contains a version of pybind11 that is pinned to a git submodule that is 2+ years old and won't work with Python 3.11.

### PR DESCRIPTION
**Pull request by apowers313**
Fixes #361 by updating the pybind11 module to the [v2.11.1](https://github.com/pybind/pybind11/releases/tag/v2.11.1) tag.

### CODE REVIEW

**Comment by condnsdmatters** [comment]
You'll have to approve the contributor license agreement.

**Comment by apowers313** [comment]
CLA signed

**Comment by jsuarez5341** [comment]
@cdmatters Can this be merged? Would like to ship NLE in a container with 3.11 and this is blocking

**Comment by heiner** [comment]
@samvelyan might be able to approve.

**Review by samvelyan — APPROVED** [review]

**Comment by jsuarez5341** [comment]
Awesome! Looks like the automated build is failing, any chance of an updated pypi package?

**Comment by jsuarez5341** [comment]
@samvelyan Any chance of updating the pip package?

**Comment by jsuarez5341** [comment]
@samvelyan Any word on this? Shipping NLE source in our containers for now, would be nice to have the pip package
